/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedInvestigationsIndexRouteImport } from './routes/_authenticated/investigations.index'
import { Route as AuthenticatedProductsModelIdRouteImport } from './routes/_authenticated/products.$modelId'
import { Route as AuthenticatedInvestigationsIdRouteImport } from './routes/_authenticated/investigations.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminMlRouteImport } from './routes/_authenticated/admin/ml'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminIngestionRouteImport } from './routes/_authenticated/admin/ingestion'
import { Route as AuthenticatedAdminMlIdRouteImport } from './routes/_authenticated/admin/ml.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestigationsIndexRoute =
  AuthenticatedInvestigationsIndexRouteImport.update({
    id: '/investigations/',
    path: '/investigations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsModelIdRoute =
  AuthenticatedProductsModelIdRouteImport.update({
    id: '/products/$modelId',
    path: '/products/$modelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestigationsIdRoute =
  AuthenticatedInvestigationsIdRouteImport.update({
    id: '/investigations/$id',
    path: '/investigations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMlRoute = AuthenticatedAdminMlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminIngestionRoute =
  AuthenticatedAdminIngestionRouteImport.update({
    id: '/ingestion',
    path: '/ingestion',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMlIdRoute = AuthenticatedAdminMlIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminMlRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/ml': typeof AuthenticatedAdminMlRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/investigations/$id': typeof AuthenticatedInvestigationsIdRoute
  '/products/$modelId': typeof AuthenticatedProductsModelIdRoute
  '/investigations/': typeof AuthenticatedInvestigationsIndexRoute
  '/admin/ml/$id': typeof AuthenticatedAdminMlIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/ml': typeof AuthenticatedAdminMlRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/investigations/$id': typeof AuthenticatedInvestigationsIdRoute
  '/products/$modelId': typeof AuthenticatedProductsModelIdRoute
  '/investigations': typeof AuthenticatedInvestigationsIndexRoute
  '/admin/ml/$id': typeof AuthenticatedAdminMlIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/ml': typeof AuthenticatedAdminMlRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/investigations/$id': typeof AuthenticatedInvestigationsIdRoute
  '/_authenticated/products/$modelId': typeof AuthenticatedProductsModelIdRoute
  '/_authenticated/investigations/': typeof AuthenticatedInvestigationsIndexRoute
  '/_authenticated/admin/ml/$id': typeof AuthenticatedAdminMlIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/ranking'
    | '/admin/ingestion'
    | '/admin/logs'
    | '/admin/ml'
    | '/admin/users'
    | '/investigations/$id'
    | '/products/$modelId'
    | '/investigations/'
    | '/admin/ml/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/ranking'
    | '/admin/ingestion'
    | '/admin/logs'
    | '/admin/ml'
    | '/admin/users'
    | '/investigations/$id'
    | '/products/$modelId'
    | '/investigations'
    | '/admin/ml/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/_authenticated/ranking'
    | '/_authenticated/admin/ingestion'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/ml'
    | '/_authenticated/admin/users'
    | '/_authenticated/investigations/$id'
    | '/_authenticated/products/$modelId'
    | '/_authenticated/investigations/'
    | '/_authenticated/admin/ml/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigations/': {
      id: '/_authenticated/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof AuthenticatedInvestigationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$modelId': {
      id: '/_authenticated/products/$modelId'
      path: '/products/$modelId'
      fullPath: '/products/$modelId'
      preLoaderRoute: typeof AuthenticatedProductsModelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investigations/$id': {
      id: '/_authenticated/investigations/$id'
      path: '/investigations/$id'
      fullPath: '/investigations/$id'
      preLoaderRoute: typeof AuthenticatedInvestigationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ml': {
      id: '/_authenticated/admin/ml'
      path: '/ml'
      fullPath: '/admin/ml'
      preLoaderRoute: typeof AuthenticatedAdminMlRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ingestion': {
      id: '/_authenticated/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AuthenticatedAdminIngestionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ml/$id': {
      id: '/_authenticated/admin/ml/$id'
      path: '/$id'
      fullPath: '/admin/ml/$id'
      preLoaderRoute: typeof AuthenticatedAdminMlIdRouteImport
      parentRoute: typeof AuthenticatedAdminMlRoute
    }
  }
}

interface AuthenticatedAdminMlRouteChildren {
  AuthenticatedAdminMlIdRoute: typeof AuthenticatedAdminMlIdRoute
}

const AuthenticatedAdminMlRouteChildren: AuthenticatedAdminMlRouteChildren = {
  AuthenticatedAdminMlIdRoute: AuthenticatedAdminMlIdRoute,
}

const AuthenticatedAdminMlRouteWithChildren =
  AuthenticatedAdminMlRoute._addFileChildren(AuthenticatedAdminMlRouteChildren)

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIngestionRoute: typeof AuthenticatedAdminIngestionRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminMlRoute: typeof AuthenticatedAdminMlRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIngestionRoute: AuthenticatedAdminIngestionRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminMlRoute: AuthenticatedAdminMlRouteWithChildren,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedInvestigationsIdRoute: typeof AuthenticatedInvestigationsIdRoute
  AuthenticatedProductsModelIdRoute: typeof AuthenticatedProductsModelIdRoute
  AuthenticatedInvestigationsIndexRoute: typeof AuthenticatedInvestigationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedInvestigationsIdRoute: AuthenticatedInvestigationsIdRoute,
  AuthenticatedProductsModelIdRoute: AuthenticatedProductsModelIdRoute,
  AuthenticatedInvestigationsIndexRoute: AuthenticatedInvestigationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
